class AlreadyTerminatedException(Exception):
    pass

class ThreadException(Exception):
    pass